# Generated by Django 5.0.7 on 2024-08-02 18:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceUpdate",
            fields=[
                ("update_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ts", models.DateTimeField()),
                ("rid", models.CharField(max_length=30)),
                ("uid", models.CharField(max_length=10)),
                ("passenger", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("update_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("time", models.TimeField()),
                ("tpl", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=10)),
                (
                    "service_update",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="trainapi.serviceupdate"),
                ),
            ],
        ),
    ]
