# Generated by Django 5.0.7 on 2024-08-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="service_update",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="locations", to="trainapi.serviceupdate"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["time"], name="trainapi_lo_time_c26bca_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["tpl"], name="trainapi_lo_tpl_7dc0ee_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["type"], name="trainapi_lo_type_39a42c_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceupdate",
            index=models.Index(fields=["ts"], name="trainapi_se_ts_1d39f5_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceupdate",
            index=models.Index(fields=["rid"], name="trainapi_se_rid_8eb72d_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceupdate",
            index=models.Index(fields=["uid"], name="trainapi_se_uid_c087ef_idx"),
        ),
    ]
