services:
  db:
    env_file: .env
    image: postgres
    restart: always
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
